---
language: node_js
node_js:
  - '12'

sudo: false

dist: trusty

cache:
  yarn: true

before_install:
  # travis includes an old yarn with more bugs
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn lint
  - JOBS=1 yarn test
